// projects.js
import { reactive } from "vue";

export const projects = reactive([
  {
    id: 1,
    mainImage: "/images/projects/01/main.jpg",
    title: "Red House International School",
    text: "Lorem ipsum dolot sit amet",
    tags: ["arquitecture"],
    carousel_images: [
      { url: "/images/projects/01/img1.jpg" },
      { url: "/images/projects/01/img2.jpg" },
      { url: "/images/projects/01/img3.jpg" },
      { url: "/images/projects/01/planta-terreo.jpg" },
      { url: "/images/projects/01/planta-2pav.jpg" },
      { url: "/images/projects/01/corte-longitudinal.jpg" },
      { url: "/images/projects/01/corte-transversal.jpg" },
    ],
    extra_images: [{ url: "/images/projects/01/extra_img1.jpg" }],
  },
  {
    id: 2,
    mainImage: "/images/projects/02/gio-capa.jpg",
    title: "Edificio Vicente Giordano",
    text: "Description of Project 2",
    tags: ["arquitecture", "legal"],
    carousel_images: [
      { url: "/images/projects/02/gio-ext1.jpg" },
      { url: "/images/projects/02/gio-ext2.jpg" },
      { url: "/images/projects/02/gio-int-dia.jpg" },
      { url: "/images/projects/02/gio-int-nt.jpg" },
      { url: "/images/projects/02/gio-bar-nt2.jpg" },
      { url: "/images/projects/02/gio-pla.jpg" },
      { url: "/images/projects/02/gio-elv1.jpg" },
    ],
  },
  {
    id: 3,
    mainImage: "images/projects/03/thumbnail.jpg",
    title: "Alagoas",
    text: "Description of Project 3",
    tags: ["arquitecture", "legal", "obra"],
    carousel_images: [
      { url: "/images/projects/03/alg-3d4.jpg" },
      { url: "/images/projects/03/alg-3d-2.jpg" },
      { url: "/images/projects/03/alg-3d-3.jpg" },
      { url: "/images/projects/03/main.jpg" },
      { url: "/images/projects/03/alg-pla-ter.jpg" },
      { url: "/images/projects/03/alg-pla-1p.jpg" },
      { url: "/images/projects/03/alg-pla-cob.jpg" },
      { url: "/images/projects/03/alg-corte.jpg" },
    ],
  },
  {
    id: 4,
    mainImage: "/images/projects/04/corte.jpg",
    title: "Residencial A&T Artes",
    text: "Description of Project 4",
    tags: ["legal"],
    carousel_images: [
      { url: "/images/projects/04/pla-terreo.jpg" },
      { url: "/images/projects/04/pla-1-pav.jpg" },
      { url: "/images/projects/04/pla-tip.jpg" },
      { url: "/images/projects/04/corte.jpg" },
    ],
  },
  {
    id: 5,
    mainImage: "/images/projects/05/let-capa.jpg",
    title: "Consultório Médico",
    text: "Description of Project 5",
    tags: ["legal"],
    carousel_images: [
      { url: "/images/projects/05/PLA-LA.jpg" },
      { url: "/images/projects/05/let-3d1.jpg" },
      { url: "/images/projects/05/let-3d2.jpg" },
      { url: "/images/projects/05/let-3d3.jpg" },
    ],
  },
  {
    id: 6,
    mainImage: "/images/projects/06/mar-capa.jpg",
    title: "Galeria 25 de Março",
    text: "Description of Project 6",
    tags: ["obra"],
    carousel_images: [
      { url: "/images/projects/06/mar-1.jpg" },
      { url: "/images/projects/06/mar-2.jpg" },
      { url: "/images/projects/06/mar-3.jpg" },
      { url: "/images/projects/06/mar-4.jpg" },
      { url: "/images/projects/06/mar-5.jpg" },
      { url: "/images/projects/06/mar-6.jpg" },
      { url: "/images/projects/06/mar-7.jpg" },
      { url: "/images/projects/06/mar-8.jpg" },
    ],
  },
  {
    id: 7,
    mainImage: "/images/projects/07/hel-capa.jpg",
    title: "Residencial Maria Helena",
    text: "Description of Project 7",
    tags: ["obra"],
    carousel_images: [
      { url: "/images/projects/07/hel-1.jpg" },
      { url: "/images/projects/07/hel-2.jpg" },
      { url: "/images/projects/07/hel-3.jpg" },
      { url: "/images/projects/07/hel-5.jpg" },
      { url: "/images/projects/07/hel-7.jpg" },
      { url: "/images/projects/07/hel-9.jpg" },
      { url: "/images/projects/07/hel-10.jpg" },
      { url: "/images/projects/07/hel-11.jpg" },
      { url: "/images/projects/07/hel-12.jpg" },
      { url: "/images/projects/07/hel-13.jpg" },
      { url: "/images/projects/07/hel-14.jpg" },
    ],
  },
  {
    id: 8,
    mainImage: "/images/projects/08/eli-capa.jpg",
    title: "Av. Elísio Teixeira Leite",
    text: "Description of Project 8",
    tags: ["obra"],
    carousel_images: [
      { url: "/images/projects/08/eli-1.jpg" },
      { url: "/images/projects/08/eli-2.jpg" },
      { url: "/images/projects/08/eli-3.jpg" },
      { url: "/images/projects/08/eli-4.jpg" },
      { url: "/images/projects/08/eli-5.jpg" },
      { url: "/images/projects/08/eli-6.jpg" },
    ],
  },
  {
    id: 9,
    mainImage: "/images/projects/09/cak-capa.jpg",
    title: "Kherlakian",
    text: "Description of Project 9",
    tags: ["obra"],
    carousel_images: [
      { url: "/images/projects/09/cak-1.jpg" },
      { url: "/images/projects/09/cak-2.jpg" },
      { url: "/images/projects/09/cak-3.jpg" },
      { url: "/images/projects/09/cak-4.jpg" },
      { url: "/images/projects/09/cak-5.jpg" },
      { url: "/images/projects/09/cak-6.jpg" },
      { url: "/images/projects/09/cak-7.jpg" },
      { url: "/images/projects/09/cak-8.jpg" },
      { url: "/images/projects/09/cak-9.jpg" },
      { url: "/images/projects/09/cak-10.jpg" },
    ],
  },
]);

export const mainProjects = reactive([
  {
    id: "1",
    title: "Red House International School",
    img: "/images/projects/01/main.jpg",
    href: "portfolio/projeto/1",
  },
  {
    id: "5",
    title: "Consultório Médico",
    img: "/images/projects/05/let-capa.jpg",
    href: "/projeto/5",
  },
  {
    id: "7",
    title: "Residencial Maria Helena",
    img: "/images/projects/07/hel-capa.jpg",
    href: "/projeto/7",
  },
]);
